sudo: required

services:
    - docker

script:
    - docker run -v $PWD:/ada-interfaces -t jklmnn/componolit-ci /ada-interfaces/test/genode.sh
    - docker run -v $PWD:/ada-interfaces -t jklmnn/componolit-ci /ada-interfaces/test/linux.sh
      #    - docker run -v $PWD:/ada-interfaces -t jklmnn/componolit-ci /ada-interfaces/test/muen.sh
