sudo: required

language: c

services:
    - docker

env:
    - TEST_SUITE=linux
    - TEST_SUITE=genode

script:
    - if [ "$TEST_SUITE" = "genode" ]; then docker run -v $PWD:/gneiss -t jklmnn/componolit-ci:latest-genode /gneiss/test/genode.sh; fi
    - if [ "$TEST_SUITE" = "linux" ]; then docker run -v $PWD:/gneiss -t jklmnn/componolit-ci:latest-gnat /gneiss/test/linux.sh; fi
