sudo: true
language: c
git:
    submodules: true
before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential git wget libfontconfig1 libx11-xcb1
before_script:
    - wget http://mirrors.cdn.adacore.com/art/5b0d7bffa3f5d709751e3e04 -O /tmp/gnat-community-2018-20180528-x86_64-linux-bin
    - git clone https://github.com/AdaCore/gnat_community_install_script.git /tmp/gnat_community_install_script
    - /tmp/gnat_community_install_script/install_package.sh /tmp/gnat-community-2018-20180528-x86_64-linux-bin /usr/local/gnat
env:
    - PATH=/usr/local/gnat/bin:$PATH
script:
    - cd ada-runtime
    - make && make platform
    - cd ..
    - mkdir -p contrib/lib/sparkcrypto
    - gprbuild -P contrib/libsparkcrypto.gpr -XOPERATION=compile
    - gprbuild -P ada_interface.gpr -XPLATFORM=genode
    - gprbuild -P ada_interface.gpr -XPLATFORM=posix -XTEST=hello_world
    - gnatprove -P ada_interface.gpr -j0 --level=2 --checks-as-errors -XPLATFORM=genode
    - gnatprove -P ada_interface.gpr -j0 --level=2 --checks-as-errors -XPLATFORM=posix
