name: CI

on: push

jobs:
    gnat_community_2019:
        name: gnat-community-2019
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: GNAT Community 2019
              run: docker run -v $PWD:/gneiss componolit/ci:gnat-community-2019 /bin/sh -c "/gneiss/test/linux.sh"
    gnat_community_2020:
        name: gnat-community-2020
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: GNAT Community 2020
              run: docker run -v $PWD:/gneiss componolit/ci:gnat-community-2020 /bin/sh -c "/gneiss/test/linux.sh"
    genode:
        name: Genode
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Genode
              run: docker run -v $PWD:/gneiss componolit/ci:genode /bin/sh -c "/gneiss/test/genode.sh"
